name: Docker Hub Deployment

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  schedule:
    - cron: '0 0 14,28 * *'
  workflow_dispatch:

jobs:
  build:
    name: Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository Files
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Publish Docker Image
        uses: docker/build-push-action@v2
        with:
          context: './dockerfile/'
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/docker-latex:latest
